version: '3.4'

services:
  gatewayapi:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: GatewayAPI/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - identityapi
      - vehiclecatalogapi

  identityapi:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: IdentityAPI/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - sqlserver

  vehiclecatalogapi:
    image: ${DOCKER_REGISTRY-}vehiclecatalogapi
    build:
      context: .
      dockerfile: VehicleCatalogAPI/Dockerfile
    ports:
      - "5002:80"
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=/Password123
    ports:
      - "1433:1433"
    volumes:
      - ./sqlserver-data:/var/opt/mssql/data