// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleCatalogAPI.Models;

#nullable disable

namespace VehicleCatalogAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230605151356_ExtraSeed")]
    partial class ExtraSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehicleCatalogAPI.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Day")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Doors")
                        .HasColumnType("int");

                    b.Property<bool>("Electric")
                        .HasColumnType("bit");

                    b.Property<decimal>("Hour")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Power")
                        .HasColumnType("float");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<int>("Transmission")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<decimal>("Week")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "turquoise",
                            Day = 29.5052546629170400m,
                            Doors = 2,
                            Electric = false,
                            Hour = 9.6248968412186330m,
                            Make = "Maserati",
                            Model = "Alpine",
                            Power = 311.0,
                            Seats = 7,
                            Transmission = 1,
                            Type = 3,
                            Week = 160.5087902019458000m,
                            Year = 1992
                        },
                        new
                        {
                            Id = 2,
                            Color = "yellow",
                            Day = 12.25600506574068800m,
                            Doors = 4,
                            Electric = true,
                            Hour = 14.4159399123348760m,
                            Make = "Polestar",
                            Model = "Spyder",
                            Power = 930.0,
                            Seats = 2,
                            Transmission = 1,
                            Type = 2,
                            Week = 242.3316605092364000m,
                            Year = 2014
                        },
                        new
                        {
                            Id = 3,
                            Color = "yellow",
                            Day = 44.6071792675311600m,
                            Doors = 2,
                            Electric = true,
                            Hour = 8.2894530966930410m,
                            Make = "Land Rover",
                            Model = "Challenger",
                            Power = 567.0,
                            Seats = 4,
                            Transmission = 1,
                            Type = 7,
                            Week = 142.5162439032604000m,
                            Year = 2002
                        },
                        new
                        {
                            Id = 4,
                            Color = "red",
                            Day = 44.0496196870638800m,
                            Doors = 2,
                            Electric = false,
                            Hour = 12.6787090948182440m,
                            Make = "Kia",
                            Model = "Mustang",
                            Power = 948.0,
                            Seats = 6,
                            Transmission = 2,
                            Type = 0,
                            Week = 279.3140893143196000m,
                            Year = 2019
                        },
                        new
                        {
                            Id = 5,
                            Color = "magenta",
                            Day = 25.9875487953083600m,
                            Doors = 4,
                            Electric = true,
                            Hour = 16.1023100084902340m,
                            Make = "Maserati",
                            Model = "Altima",
                            Power = 487.0,
                            Seats = 8,
                            Transmission = 2,
                            Type = 2,
                            Week = 286.7167392104758000m,
                            Year = 1980
                        },
                        new
                        {
                            Id = 6,
                            Color = "lavender",
                            Day = 20.8736406958490800m,
                            Doors = 4,
                            Electric = true,
                            Hour = 13.4100801951380010m,
                            Make = "Porsche",
                            Model = "Charger",
                            Power = 298.0,
                            Seats = 4,
                            Transmission = 1,
                            Type = 6,
                            Week = 295.6009920653302000m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 7,
                            Color = "azure",
                            Day = 41.3239384217474400m,
                            Doors = 2,
                            Electric = false,
                            Hour = 17.659709944401760m,
                            Make = "Audi",
                            Model = "Mercielago",
                            Power = 167.0,
                            Seats = 6,
                            Transmission = 0,
                            Type = 10,
                            Week = 132.1275544443862000m,
                            Year = 2015
                        },
                        new
                        {
                            Id = 8,
                            Color = "mint green",
                            Day = 24.7627382865467600m,
                            Doors = 4,
                            Electric = false,
                            Hour = 13.391698664998530m,
                            Make = "Fiat",
                            Model = "Golf",
                            Power = 230.0,
                            Seats = 8,
                            Transmission = 1,
                            Type = 5,
                            Week = 189.1690334985898000m,
                            Year = 1996
                        },
                        new
                        {
                            Id = 9,
                            Color = "sky blue",
                            Day = 21.7396140019134800m,
                            Doors = 2,
                            Electric = false,
                            Hour = 10.1958484072855010m,
                            Make = "Aston Martin",
                            Model = "Grand Cherokee",
                            Power = 601.0,
                            Seats = 5,
                            Transmission = 0,
                            Type = 1,
                            Week = 283.0047159400250000m,
                            Year = 2005
                        },
                        new
                        {
                            Id = 10,
                            Color = "pink",
                            Day = 33.3119739695690400m,
                            Doors = 4,
                            Electric = true,
                            Hour = 4.3738929563169540m,
                            Make = "Land Rover",
                            Model = "Model S",
                            Power = 994.0,
                            Seats = 4,
                            Transmission = 1,
                            Type = 4,
                            Week = 241.2613809589510000m,
                            Year = 1983
                        },
                        new
                        {
                            Id = 11,
                            Color = "tan",
                            Day = 25.3871580494541600m,
                            Doors = 4,
                            Electric = true,
                            Hour = 3.0088858207575120m,
                            Make = "Nissan",
                            Model = "Civic",
                            Power = 680.0,
                            Seats = 2,
                            Transmission = 0,
                            Type = 3,
                            Week = 195.4034605153986000m,
                            Year = 2015
                        },
                        new
                        {
                            Id = 12,
                            Color = "olive",
                            Day = 27.6547659812329200m,
                            Doors = 4,
                            Electric = false,
                            Hour = 8.4862978047796680m,
                            Make = "Jaguar",
                            Model = "Altima",
                            Power = 366.0,
                            Seats = 2,
                            Transmission = 0,
                            Type = 2,
                            Week = 270.3025007192372000m,
                            Year = 1982
                        },
                        new
                        {
                            Id = 13,
                            Color = "grey",
                            Day = 47.5443507351043200m,
                            Doors = 4,
                            Electric = true,
                            Hour = 19.6800718246914210m,
                            Make = "Bentley",
                            Model = "Colorado",
                            Power = 946.0,
                            Seats = 5,
                            Transmission = 1,
                            Type = 7,
                            Week = 140.5178485525564000m,
                            Year = 1983
                        },
                        new
                        {
                            Id = 14,
                            Color = "red",
                            Day = 25.8720657515004800m,
                            Doors = 4,
                            Electric = false,
                            Hour = 9.2701406847083680m,
                            Make = "Mini",
                            Model = "CX-9",
                            Power = 763.0,
                            Seats = 6,
                            Transmission = 0,
                            Type = 8,
                            Week = 166.1540212047992000m,
                            Year = 1981
                        },
                        new
                        {
                            Id = 15,
                            Color = "mint green",
                            Day = 46.1682693932820800m,
                            Doors = 2,
                            Electric = false,
                            Hour = 7.9611369935961950m,
                            Make = "BMW",
                            Model = "Mercielago",
                            Power = 169.0,
                            Seats = 3,
                            Transmission = 0,
                            Type = 7,
                            Week = 154.8281492856594000m,
                            Year = 2013
                        },
                        new
                        {
                            Id = 16,
                            Color = "olive",
                            Day = 41.2761426692985600m,
                            Doors = 2,
                            Electric = false,
                            Hour = 19.4338521111378730m,
                            Make = "Kia",
                            Model = "Wrangler",
                            Power = 393.0,
                            Seats = 3,
                            Transmission = 2,
                            Type = 5,
                            Week = 162.9967423123986000m,
                            Year = 2018
                        },
                        new
                        {
                            Id = 17,
                            Color = "maroon",
                            Day = 10.374286833739012800m,
                            Doors = 2,
                            Electric = false,
                            Hour = 4.6383661424051510m,
                            Make = "Bugatti",
                            Model = "XC90",
                            Power = 665.0,
                            Seats = 8,
                            Transmission = 1,
                            Type = 7,
                            Week = 118.56728221944848000m,
                            Year = 1997
                        },
                        new
                        {
                            Id = 18,
                            Color = "lime",
                            Day = 32.9676089748277600m,
                            Doors = 2,
                            Electric = false,
                            Hour = 7.4905554344938840m,
                            Make = "Dodge",
                            Model = "XC90",
                            Power = 419.0,
                            Seats = 4,
                            Transmission = 2,
                            Type = 9,
                            Week = 192.7560209136164000m,
                            Year = 1985
                        },
                        new
                        {
                            Id = 19,
                            Color = "plum",
                            Day = 33.0686011877770400m,
                            Doors = 4,
                            Electric = false,
                            Hour = 14.3357275902936980m,
                            Make = "Chevrolet",
                            Model = "Malibu",
                            Power = 693.0,
                            Seats = 8,
                            Transmission = 0,
                            Type = 7,
                            Week = 155.6975270602324000m,
                            Year = 2019
                        },
                        new
                        {
                            Id = 20,
                            Color = "lime",
                            Day = 26.422702014286400m,
                            Doors = 2,
                            Electric = false,
                            Hour = 1.49115392879476420m,
                            Make = "Volvo",
                            Model = "Grand Caravan",
                            Power = 423.0,
                            Seats = 8,
                            Transmission = 0,
                            Type = 4,
                            Week = 241.9632236278982000m,
                            Year = 1993
                        });
                });

            modelBuilder.Entity("VehicleCatalogAPI.Models.CarExtra", b =>
                {
                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("ExtraId")
                        .HasColumnType("int");

                    b.HasKey("CarId", "ExtraId");

                    b.HasIndex("ExtraId");

                    b.ToTable("CarExtras");
                });

            modelBuilder.Entity("VehicleCatalogAPI.Models.Extra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Extras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "GPS"
                        },
                        new
                        {
                            Id = 2,
                            Name = "AC"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Heated seats"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Autopilot"
                        });
                });

            modelBuilder.Entity("VehicleCatalogAPI.Models.CarExtra", b =>
                {
                    b.HasOne("VehicleCatalogAPI.Models.Car", "Car")
                        .WithMany("CarExtras")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleCatalogAPI.Models.Extra", "Extra")
                        .WithMany("CarExtras")
                        .HasForeignKey("ExtraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Extra");
                });

            modelBuilder.Entity("VehicleCatalogAPI.Models.Car", b =>
                {
                    b.Navigation("CarExtras");
                });

            modelBuilder.Entity("VehicleCatalogAPI.Models.Extra", b =>
                {
                    b.Navigation("CarExtras");
                });
#pragma warning restore 612, 618
        }
    }
}
