// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleCatalogAPI.Models;

#nullable disable

namespace VehicleCatalogAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230605152657_AddCarExtraSeed")]
    partial class AddCarExtraSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehicleCatalogAPI.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Day")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Doors")
                        .HasColumnType("int");

                    b.Property<bool>("Electric")
                        .HasColumnType("bit");

                    b.Property<decimal>("Hour")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Power")
                        .HasColumnType("float");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<int>("Transmission")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<decimal>("Week")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "blue",
                            Day = 43.3567854786498000m,
                            Doors = 4,
                            Electric = true,
                            Hour = 13.5464571315863020m,
                            Make = "Chevrolet",
                            Model = "Expedition",
                            Power = 613.0,
                            Seats = 3,
                            Transmission = 1,
                            Type = 5,
                            Week = 206.9196881359262000m,
                            Year = 2016
                        },
                        new
                        {
                            Id = 2,
                            Color = "gold",
                            Day = 39.0423830191253200m,
                            Doors = 2,
                            Electric = true,
                            Hour = 19.30829682785680m,
                            Make = "Rolls Royce",
                            Model = "2",
                            Power = 882.0,
                            Seats = 5,
                            Transmission = 0,
                            Type = 8,
                            Week = 269.9560460132542000m,
                            Year = 1988
                        },
                        new
                        {
                            Id = 3,
                            Color = "purple",
                            Day = 40.6547947213448400m,
                            Doors = 4,
                            Electric = true,
                            Hour = 4.4798307864773540m,
                            Make = "Volvo",
                            Model = "Grand Caravan",
                            Power = 654.0,
                            Seats = 7,
                            Transmission = 0,
                            Type = 0,
                            Week = 242.2264621849372000m,
                            Year = 1998
                        },
                        new
                        {
                            Id = 4,
                            Color = "violet",
                            Day = 45.5248560339300400m,
                            Doors = 4,
                            Electric = true,
                            Hour = 14.5433773008645310m,
                            Make = "Mazda",
                            Model = "Accord",
                            Power = 555.0,
                            Seats = 4,
                            Transmission = 1,
                            Type = 1,
                            Week = 125.507183691096000m,
                            Year = 2009
                        },
                        new
                        {
                            Id = 5,
                            Color = "salmon",
                            Day = 15.1792431150171200m,
                            Doors = 4,
                            Electric = true,
                            Hour = 14.9949548337398460m,
                            Make = "Mercedes Benz",
                            Model = "ATS",
                            Power = 421.0,
                            Seats = 4,
                            Transmission = 2,
                            Type = 0,
                            Week = 245.651179524976000m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 6,
                            Color = "orange",
                            Day = 14.9789215171161200m,
                            Doors = 4,
                            Electric = true,
                            Hour = 13.4868610776610220m,
                            Make = "Audi",
                            Model = "CX-9",
                            Power = 999.0,
                            Seats = 6,
                            Transmission = 0,
                            Type = 0,
                            Week = 215.2455277816430000m,
                            Year = 2010
                        },
                        new
                        {
                            Id = 7,
                            Color = "cyan",
                            Day = 37.4674995053566400m,
                            Doors = 2,
                            Electric = false,
                            Hour = 5.9011292572495150m,
                            Make = "Polestar",
                            Model = "Taurus",
                            Power = 326.0,
                            Seats = 2,
                            Transmission = 2,
                            Type = 3,
                            Week = 113.97347285213204000m,
                            Year = 2019
                        },
                        new
                        {
                            Id = 8,
                            Color = "black",
                            Day = 31.8524085022105600m,
                            Doors = 4,
                            Electric = false,
                            Hour = 14.9223836862954470m,
                            Make = "Chevrolet",
                            Model = "Cruze",
                            Power = 211.0,
                            Seats = 3,
                            Transmission = 1,
                            Type = 3,
                            Week = 172.1929696577998000m,
                            Year = 1993
                        },
                        new
                        {
                            Id = 9,
                            Color = "magenta",
                            Day = 25.9343734359880800m,
                            Doors = 2,
                            Electric = false,
                            Hour = 9.478224158278670m,
                            Make = "Jaguar",
                            Model = "Fortwo",
                            Power = 624.0,
                            Seats = 6,
                            Transmission = 1,
                            Type = 8,
                            Week = 191.5102939163978000m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 10,
                            Color = "pink",
                            Day = 48.3659580303438400m,
                            Doors = 2,
                            Electric = true,
                            Hour = 18.2998871979076930m,
                            Make = "Bugatti",
                            Model = "Ranchero",
                            Power = 570.0,
                            Seats = 4,
                            Transmission = 1,
                            Type = 4,
                            Week = 221.2424441942688000m,
                            Year = 1989
                        },
                        new
                        {
                            Id = 11,
                            Color = "plum",
                            Day = 25.6092511324434800m,
                            Doors = 4,
                            Electric = true,
                            Hour = 5.0965754566411970m,
                            Make = "Jeep",
                            Model = "A4",
                            Power = 834.0,
                            Seats = 4,
                            Transmission = 2,
                            Type = 1,
                            Week = 149.0088706036658000m,
                            Year = 1996
                        },
                        new
                        {
                            Id = 12,
                            Color = "silver",
                            Day = 31.0350200198142000m,
                            Doors = 2,
                            Electric = false,
                            Hour = 5.4697959349158310m,
                            Make = "Volkswagen",
                            Model = "ATS",
                            Power = 85.0,
                            Seats = 4,
                            Transmission = 1,
                            Type = 9,
                            Week = 265.4005528457922000m,
                            Year = 1990
                        },
                        new
                        {
                            Id = 13,
                            Color = "lime",
                            Day = 15.0798155472773200m,
                            Doors = 2,
                            Electric = false,
                            Hour = 3.3747103452788060m,
                            Make = "Honda",
                            Model = "Grand Cherokee",
                            Power = 616.0,
                            Seats = 2,
                            Transmission = 2,
                            Type = 1,
                            Week = 275.6244517853248000m,
                            Year = 2009
                        },
                        new
                        {
                            Id = 14,
                            Color = "magenta",
                            Day = 28.6928217934719200m,
                            Doors = 2,
                            Electric = false,
                            Hour = 18.9057262901767140m,
                            Make = "Maserati",
                            Model = "Model S",
                            Power = 359.0,
                            Seats = 7,
                            Transmission = 2,
                            Type = 4,
                            Week = 214.7107222148124000m,
                            Year = 1986
                        },
                        new
                        {
                            Id = 15,
                            Color = "purple",
                            Day = 31.1486945487898800m,
                            Doors = 2,
                            Electric = true,
                            Hour = 19.2419890197637560m,
                            Make = "Nissan",
                            Model = "Grand Caravan",
                            Power = 117.0,
                            Seats = 4,
                            Transmission = 1,
                            Type = 3,
                            Week = 291.3199643554496000m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 16,
                            Color = "cyan",
                            Day = 41.3779863736070000m,
                            Doors = 2,
                            Electric = false,
                            Hour = 13.9246563779750570m,
                            Make = "Dodge",
                            Model = "Jetta",
                            Power = 937.0,
                            Seats = 4,
                            Transmission = 1,
                            Type = 4,
                            Week = 294.8710105520848000m,
                            Year = 2006
                        },
                        new
                        {
                            Id = 17,
                            Color = "azure",
                            Day = 49.1816621805397200m,
                            Doors = 2,
                            Electric = true,
                            Hour = 14.466361051275050m,
                            Make = "Smart",
                            Model = "A4",
                            Power = 671.0,
                            Seats = 7,
                            Transmission = 0,
                            Type = 2,
                            Week = 242.8501836205544000m,
                            Year = 2001
                        },
                        new
                        {
                            Id = 18,
                            Color = "silver",
                            Day = 27.0150984972475600m,
                            Doors = 2,
                            Electric = true,
                            Hour = 3.0723676353806520m,
                            Make = "Fiat",
                            Model = "Focus",
                            Power = 935.0,
                            Seats = 6,
                            Transmission = 2,
                            Type = 3,
                            Week = 163.655081094104000m,
                            Year = 1993
                        },
                        new
                        {
                            Id = 19,
                            Color = "violet",
                            Day = 24.9102244660538800m,
                            Doors = 4,
                            Electric = false,
                            Hour = 3.7069090551739840m,
                            Make = "Ferrari",
                            Model = "A4",
                            Power = 209.0,
                            Seats = 8,
                            Transmission = 2,
                            Type = 10,
                            Week = 187.4436411096988000m,
                            Year = 1995
                        },
                        new
                        {
                            Id = 20,
                            Color = "lavender",
                            Day = 24.1503939251612800m,
                            Doors = 2,
                            Electric = false,
                            Hour = 16.0863899414939940m,
                            Make = "Honda",
                            Model = "Altima",
                            Power = 219.0,
                            Seats = 4,
                            Transmission = 0,
                            Type = 7,
                            Week = 173.7463637493528000m,
                            Year = 2015
                        });
                });

            modelBuilder.Entity("VehicleCatalogAPI.Models.CarExtra", b =>
                {
                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("ExtraId")
                        .HasColumnType("int");

                    b.HasKey("CarId", "ExtraId");

                    b.HasIndex("ExtraId");

                    b.ToTable("CarExtras");

                    b.HasData(
                        new
                        {
                            CarId = 2,
                            ExtraId = 1
                        },
                        new
                        {
                            CarId = 2,
                            ExtraId = 2
                        },
                        new
                        {
                            CarId = 2,
                            ExtraId = 3
                        },
                        new
                        {
                            CarId = 3,
                            ExtraId = 1
                        },
                        new
                        {
                            CarId = 3,
                            ExtraId = 2
                        },
                        new
                        {
                            CarId = 4,
                            ExtraId = 1
                        },
                        new
                        {
                            CarId = 4,
                            ExtraId = 2
                        },
                        new
                        {
                            CarId = 5,
                            ExtraId = 1
                        },
                        new
                        {
                            CarId = 5,
                            ExtraId = 2
                        },
                        new
                        {
                            CarId = 5,
                            ExtraId = 3
                        },
                        new
                        {
                            CarId = 5,
                            ExtraId = 4
                        },
                        new
                        {
                            CarId = 6,
                            ExtraId = 1
                        },
                        new
                        {
                            CarId = 6,
                            ExtraId = 2
                        },
                        new
                        {
                            CarId = 6,
                            ExtraId = 3
                        },
                        new
                        {
                            CarId = 7,
                            ExtraId = 1
                        },
                        new
                        {
                            CarId = 8,
                            ExtraId = 1
                        },
                        new
                        {
                            CarId = 8,
                            ExtraId = 2
                        },
                        new
                        {
                            CarId = 10,
                            ExtraId = 1
                        },
                        new
                        {
                            CarId = 11,
                            ExtraId = 1
                        },
                        new
                        {
                            CarId = 11,
                            ExtraId = 2
                        },
                        new
                        {
                            CarId = 11,
                            ExtraId = 3
                        },
                        new
                        {
                            CarId = 12,
                            ExtraId = 1
                        },
                        new
                        {
                            CarId = 13,
                            ExtraId = 1
                        },
                        new
                        {
                            CarId = 13,
                            ExtraId = 2
                        },
                        new
                        {
                            CarId = 13,
                            ExtraId = 3
                        },
                        new
                        {
                            CarId = 13,
                            ExtraId = 4
                        },
                        new
                        {
                            CarId = 14,
                            ExtraId = 1
                        },
                        new
                        {
                            CarId = 14,
                            ExtraId = 2
                        },
                        new
                        {
                            CarId = 14,
                            ExtraId = 3
                        },
                        new
                        {
                            CarId = 14,
                            ExtraId = 4
                        },
                        new
                        {
                            CarId = 15,
                            ExtraId = 1
                        },
                        new
                        {
                            CarId = 16,
                            ExtraId = 1
                        },
                        new
                        {
                            CarId = 16,
                            ExtraId = 2
                        },
                        new
                        {
                            CarId = 17,
                            ExtraId = 1
                        },
                        new
                        {
                            CarId = 17,
                            ExtraId = 2
                        },
                        new
                        {
                            CarId = 18,
                            ExtraId = 1
                        },
                        new
                        {
                            CarId = 18,
                            ExtraId = 2
                        },
                        new
                        {
                            CarId = 18,
                            ExtraId = 3
                        },
                        new
                        {
                            CarId = 19,
                            ExtraId = 1
                        },
                        new
                        {
                            CarId = 19,
                            ExtraId = 2
                        },
                        new
                        {
                            CarId = 20,
                            ExtraId = 1
                        },
                        new
                        {
                            CarId = 20,
                            ExtraId = 2
                        },
                        new
                        {
                            CarId = 20,
                            ExtraId = 3
                        });
                });

            modelBuilder.Entity("VehicleCatalogAPI.Models.Extra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Extras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "GPS"
                        },
                        new
                        {
                            Id = 2,
                            Name = "AC"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Heated seats"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Autopilot"
                        });
                });

            modelBuilder.Entity("VehicleCatalogAPI.Models.CarExtra", b =>
                {
                    b.HasOne("VehicleCatalogAPI.Models.Car", "Car")
                        .WithMany("CarExtras")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleCatalogAPI.Models.Extra", "Extra")
                        .WithMany("CarExtras")
                        .HasForeignKey("ExtraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Extra");
                });

            modelBuilder.Entity("VehicleCatalogAPI.Models.Car", b =>
                {
                    b.Navigation("CarExtras");
                });

            modelBuilder.Entity("VehicleCatalogAPI.Models.Extra", b =>
                {
                    b.Navigation("CarExtras");
                });
#pragma warning restore 612, 618
        }
    }
}
