name: Build and Check Containers
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-check-containers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run services
        run: |
          docker-compose build
          docker-compose up -d

      - name: Check container status
        run: docker-compose ps

      - name: Clean up
        run: docker-compose down
        
  run-xunit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build project
        run: dotnet build --configuration Release --no-restore
      - name: Run IdentityAPI unit tests
        run: dotnet test --logger:xunit --no-build --configuration Release IdentityAPI.Tests/IdentityAPI.Tests.csproj
